### ISSUE TITLE
Set up screenreader support, a11y checklist

### ISSUE THREAD

**Issue by tmfrnz** [unfolddata/ogdd#4]
also see https://a11yproject.com/checklist

### Landmarks
- [x] header role="banner"
- [x] nav role="navigation"
- [x] main role="main"
 
### Links
- [x] skip content link
- [x] Ensure links have :focus state. 
- [x] Ensure links are recognizable (underlined). 

### Images 
- [x] use `alt` text

### Navigation
- [x] provide navigation feedback message
- [x] set focus on navigation
- [x] set page title
- [x] ensure logical tab order

### Data visualisations
- [x] render data table for screenreaders

**Comment by tmfrnz** [comment]
- [ ] allow keyboard navigation on FA Card

**Comment by tmfrnz** [comment]
- [ ] Announce data loading start and finish
